#Requires -Version 7.0
[CmdletBinding()]param([Parameter(Mandatory)][string]$Story,[string]$ProjectRoot)
$ErrorActionPreference='Stop';if([string]::IsNullOrWhiteSpace($ProjectRoot)){$ProjectRoot=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '../../../..'))}
. (Join-Path $PSScriptRoot 'PipelineCommon.ps1');. (Join-Path $PSScriptRoot 'PipelineTransactions.ps1');Assert-ProductionBranch $ProjectRoot
$dir=Join-Path $ProjectRoot "stories/$Story";$record=Read-PipelineJson(Join-Path $dir 'story.json');if($record.provenance-cne'pipeline'-or$record.stage-cne'final-review'-or$record.status-cne'in-progress'){throw 'Candidate completion requires a pipeline story at final-review/in-progress.'}
$cert=Get-ReviewCertification(Join-Path $dir '04-review.md');if($cert.verdict-cne'PASS'){throw 'Candidate completion requires final PASS.'};$checks=@(& (Join-Path $PSScriptRoot 'Test-StoryNames.ps1') -Story $Story -Phase Final -OutputFormat Json -ProjectRoot $ProjectRoot 2>&1);$nameOk=$?;if(-not $nameOk){throw 'Final name gate failed.'};& (Join-Path $PSScriptRoot 'Test-StoryHandoffs.ps1') -Story $Story -RequireReleaseChain -OutputFormat Json -ProjectRoot $ProjectRoot *> $null;$handoffOk=$?;if(-not $handoffOk){throw 'Release handoff chain failed.'};& (Join-Path $PSScriptRoot 'New-AuthorityManifest.ps1') -Story $Story -Verify -OutputFormat Json -ProjectRoot $ProjectRoot *> $null;$authorityOk=$?;if(-not $authorityOk){throw 'Authority inventory is stale.'}
$paths=@("stories/$Story/story.json","stories/$Story/README.md","stories/$Story/release.json",'stories/INDEX.md')
Invoke-PipelineTransaction -ProjectRoot $ProjectRoot -Path $paths -Mutation {$record.stage='candidate';$record.status='candidate';Write-PipelineJson(Join-Path $dir 'story.json')$record;Set-StoryReadmeProjection(Join-Path $dir 'README.md')$record;Set-StoryIndexProjection(Join-Path $ProjectRoot 'stories/INDEX.md')$record 'Release-certified story candidate.';& (Join-Path $PSScriptRoot 'New-StoryRelease.ps1') -Story $Story -ProjectRoot $ProjectRoot *> $null;& (Join-Path $PSScriptRoot 'Test-StoryIntegrity.ps1') -Story $Story -OutputFormat Json -ProjectRoot $ProjectRoot *> $null;$postconditionOk=$?;if(-not $postconditionOk){throw 'Candidate postcondition failed.'}}
[ordered]@{schemaVersion=1;story=$Story;stage='candidate';status='candidate'}|ConvertTo-Json
