#Requires -Version 7.0
[CmdletBinding()]param([Parameter(Mandatory)][string]$GuardId,[Parameter(Mandatory)][ValidateSet('READY','HANDOFF_ERROR','USER_RULING_REQUIRED','NAME_REGISTRATION_REQUIRED')][string]$Status,[Parameter(Mandatory)][string]$ReportText,[AllowNull()][string]$ErrorCode,[AllowNull()][string]$ResolutionOwner,[AllowNull()][string]$ResolutionQuestion,[string]$ProjectRoot)
$ErrorActionPreference='Stop';if([string]::IsNullOrWhiteSpace($ProjectRoot)){$ProjectRoot=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '../../../..'))}
. (Join-Path $PSScriptRoot 'PipelineCommon.ps1');Assert-ProductionBranch $ProjectRoot;$lockDir=Join-Path $ProjectRoot '.story-locks';$lock=Join-Path $lockDir 'repository.lock';$guardPath=Join-Path $lockDir "$GuardId.json"
if(-not(Test-Path $lock)-or-not(Test-Path $guardPath)){throw 'Guard is not active.'};if((Get-Content $lock -Raw).Trim()-cne$GuardId){throw 'Guard lock identity is invalid.'};$g=Read-PipelineJson $guardPath
$contract=Get-PipelineContract $ProjectRoot;$mc=$contract.handoffLedger.modeContracts.PSObject.Properties[[string]$g.mode].Value;if($Status-cnotin@($mc.statuses)){throw 'Status is invalid for the guarded mode.'};if($ReportText-notmatch"(?m)^status: $([regex]::Escape($Status))\s*$"){throw 'Report text status does not match completion status.'}
if($Status-ceq'READY'){if($ErrorCode-or$ResolutionOwner-or$ResolutionQuestion){throw 'READY handoff cannot carry error or resolution fields.'}}else{if([string]::IsNullOrWhiteSpace($ErrorCode)-or[string]::IsNullOrWhiteSpace($ResolutionOwner)){throw 'Non-ready handoff requires errorCode and resolutionOwner.'};if($Status-ceq'USER_RULING_REQUIRED'-and[string]::IsNullOrWhiteSpace($ResolutionQuestion)){throw 'User ruling handoff requires resolutionQuestion.'}}
$changed=if($g.branch){$tracked=@(& git -C $ProjectRoot diff --name-only HEAD|ForEach-Object{$_.Replace('\','/')});$untracked=@(& git -C $ProjectRoot ls-files --others --exclude-standard|ForEach-Object{$_.Replace('\','/')});@($tracked+$untracked|Sort-Object -Unique)}else{@($g.allowedPaths|Where-Object{Test-Path -LiteralPath (Join-Path $ProjectRoot $_)})}
$ledgerRel="stories/$($g.story)/handoffs.json";$unauthorized=@($changed|Where-Object{$_-cnotin@($g.allowedPaths)-and$_-cne$ledgerRel});if($unauthorized.Count){throw "Guard found changes outside its allowlist: $($unauthorized -join ', ')"}
$outputs=@($changed|Where-Object{$_-cin@($g.allowedPaths)}|Sort-Object -Unique);if($Status-ceq'READY'-and$mc.requireAllReadyOutputs-and@($g.allowedPaths|Where-Object{$_-cnotin$outputs}).Count){throw 'READY completion did not change every required output.'}
$ledgerPath=Join-Path $ProjectRoot $ledgerRel;$ledger=Read-PipelineJson $ledgerPath;$entry=[ordered]@{sequence=@($ledger.entries).Count+1;story=[string]$g.story;actor=[string]$g.actor;mode=[string]$g.mode;status=$Status;startedAt=[string]$g.createdAt;completedAt=[DateTimeOffset]::UtcNow.ToString('o');guardId=$GuardId;persister=[string]$g.persister;report=$ReportText.Replace("`r`n","`n").Replace("`r","`n");inputs=@($g.inputs);outputs=$outputs;errorCode=$(if($ErrorCode){$ErrorCode}else{$null});resolutionOwner=$(if($ResolutionOwner){$ResolutionOwner}else{$null});resolutionQuestion=$(if($ResolutionQuestion){$ResolutionQuestion}else{$null})};$ledger.entries=@($ledger.entries)+@($entry);Write-PipelineJson $ledgerPath $ledger
Remove-Item -LiteralPath $guardPath,$lock -Force;[ordered]@{schemaVersion=1;story=$g.story;guardId=$GuardId;sequence=$entry.sequence;status=$Status;outputs=$outputs}|ConvertTo-Json -Depth 8