#Requires -Version 7.0
[CmdletBinding(SupportsShouldProcess)]param([string]$ProjectRoot)
$ErrorActionPreference='Stop';if([string]::IsNullOrWhiteSpace($ProjectRoot)){$ProjectRoot=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '../../../..'))}
. (Join-Path $PSScriptRoot 'PipelineCommon.ps1');. (Join-Path $PSScriptRoot 'PipelineTransactions.ps1');Assert-ProductionBranch $ProjectRoot
$dirs=@(Get-ChildItem -LiteralPath (Join-Path $ProjectRoot 'stories')-Directory|Where-Object Name -ne '_template'|Sort-Object Name);if($dirs.Count-ne24){throw "Legacy acceptance requires exactly 24 existing story records; found $($dirs.Count)."}
$crown='a-crown-of-quiet-hours';$paths=[Collections.Generic.List[string]]::new();foreach($d in $dirs){$paths.Add("stories/$($d.Name)/story.json");$paths.Add("stories/$($d.Name)/release.json")};foreach($p in @("stories/$crown/README.md",'stories/INDEX.md','stories/NAMES.md','stories/legacy-acceptance.json')){$paths.Add($p)}
if(-not$PSCmdlet.ShouldProcess('24 legacy story records','record RGBKnights acceptance and migrate releases')){return}
Invoke-PipelineTransaction -ProjectRoot $ProjectRoot -Path $paths -Mutation {
 $accepted=[Collections.Generic.List[object]]::new();$acceptedAt='2026-08-02T12:00:00-04:00'
 foreach($d in $dirs){$slug=$d.Name;$storyPath=Join-Path $d.FullName 'story.json';$old=Read-PipelineJson $storyPath
  if($slug-cne$crown-and($old.status-cne'final'-or-not$old.canon-or-not$old.publish)){throw "$slug is not an already-finalized legacy story."}
  $record=[ordered]@{schemaVersion=2;slug=$slug;title=[string]$old.title;created=[string]$old.created;stage='final';status='final';canon=$true;userDisposition='accepted';publish=$true;promotionDate='2026-08-01';provenance='legacy-user-attested'};Write-PipelineJson $storyPath $record
  $oldRelease=Read-PipelineJson(Join-Path $d.FullName 'release.json');$cert=Get-ReviewCertification(Join-Path $d.FullName '04-review.md');$pass=if($cert.pass-gt0){$cert.pass}elseif($oldRelease.review.pass){[int]$oldRelease.review.pass}else{1};$reviewer=if($oldRelease.review.reviewer){[string]$oldRelease.review.reviewer}else{'continuity_critic'};$reviewedAt=if($cert.updated-match'^\d{4}-\d{2}-\d{2}$'){"$($cert.updated)T00:00:00Z"}else{$acceptedAt};$certifiedAt=if($oldRelease.certifiedAt -and (Test-PipelineTimestamp $oldRelease.certifiedAt)){[string]$oldRelease.certifiedAt}else{$acceptedAt};$checkedAt=if($oldRelease.nameCheck.checkedAt -and (Test-PipelineTimestamp $oldRelease.nameCheck.checkedAt)){[string]$oldRelease.nameCheck.checkedAt}else{$acceptedAt}
  $release=[ordered]@{schemaVersion=3;certified=$true;storySlug=$slug;certifiedAt=$certifiedAt;certificationBasis='legacy-user-attested';artifacts=[ordered]@{story=[ordered]@{path='05-story.md'};canonDelta=[ordered]@{path='06-canon-delta.md'}};review=[ordered]@{artifact='05-story.md';pass=$pass;verdict='PASS';reviewer=$reviewer;reviewedAt=$reviewedAt;reviewBasis='RGBKnights legacy user acceptance';unresolvedCritical=0;unresolvedMajor=0};nameCheck=[ordered]@{story=$slug;phase='Final';passed=$true;checkedAt=$checkedAt;checkerVersion='story-names/3';warnings=@()};dependencies=[ordered]@{authorityManifest=$null;handoffLedger=$null}};Write-PipelineJson(Join-Path $d.FullName 'release.json')$release
  $accepted.Add([ordered]@{slug=$slug;promotionDate='2026-08-01'})
 }
 $manifest=[ordered]@{schemaVersion=1;acceptedBy='RGBKnights';acceptedAt=$acceptedAt;reviewBasis='User confirmed personal review and final acceptance of the 23 existing canon stories and corrected A Crown of Quiet Hours as accepted canon.';stories=@($accepted)};Write-PipelineJson(Join-Path $ProjectRoot 'stories/legacy-acceptance.json')$manifest
 $crownRecord=Read-PipelineJson(Join-Path $ProjectRoot "stories/$crown/story.json");Set-StoryReadmeProjection(Join-Path $ProjectRoot "stories/$crown/README.md")$crownRecord;Set-StoryIndexProjection(Join-Path $ProjectRoot 'stories/INDEX.md')$crownRecord 'User-corrected legacy classification; personally reviewed, finalized, canon, and published.';Set-StoryRegistryState(Join-Path $ProjectRoot 'stories/NAMES.md')$crown 'canon' 'User-corrected legacy acceptance;'
 $namesPath=Join-Path $ProjectRoot 'stories/NAMES.md';$names=Get-Content $namesPath -Raw;$names=[regex]::Replace($names,'(?m)^Last reconciled: .*?$','Last reconciled: 2026-08-02.');[IO.File]::WriteAllText($namesPath,$names.Replace("`r`n","`n").Replace("`r","`n"),[Text.UTF8Encoding]::new($false))
}
[ordered]@{schemaVersion=1;acceptedBy='RGBKnights';acceptedStories=24;crownCorrected=$true}|ConvertTo-Json
