#Requires -Version 7.0
[CmdletBinding()]param([Parameter(Mandatory)][string]$Story,[string]$ProjectRoot)
$ErrorActionPreference='Stop';if([string]::IsNullOrWhiteSpace($ProjectRoot)){$ProjectRoot=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '../../../..'))}
. (Join-Path $PSScriptRoot 'PipelineCommon.ps1');. (Join-Path $PSScriptRoot 'ReviewContracts.ps1');Assert-ProductionBranch $ProjectRoot
$dir=Join-Path $ProjectRoot "stories/$Story";$record=Read-PipelineJson(Join-Path $dir 'story.json');if($record.provenance-cne'pipeline'){throw 'Legacy releases are issued only by the explicit legacy-acceptance transaction.'};if($record.status-cnotin@('candidate','final')){throw 'Release requires candidate or final lifecycle state.'}
$reviewFile=Join-Path $dir '04-review.md';$cert=Get-ReviewCertification $reviewFile;if($cert.verdict-cne'PASS'-or$cert.pass-lt 1){throw 'Final review certification is not PASS.'}
$nameRaw=@(& (Join-Path $PSScriptRoot 'Test-StoryNames.ps1') -Story $Story -Phase Final -OutputFormat Json -ProjectRoot $ProjectRoot);$nameOk=$?;if(-not $nameOk){throw 'Final name check failed.'};$name=$nameRaw|ConvertFrom-Json
$handoffRaw=@(& (Join-Path $PSScriptRoot 'Test-StoryHandoffs.ps1') -Story $Story -RequireReleaseChain -OutputFormat Json -ProjectRoot $ProjectRoot);$handoffOk=$?;if(-not $handoffOk){throw 'Handoff release chain failed.'}
& (Join-Path $PSScriptRoot 'New-AuthorityManifest.ps1') -Story $Story -Verify -OutputFormat Json -ProjectRoot $ProjectRoot *> $null;$authorityOk=$?;if(-not $authorityOk){throw 'Authority inventory is stale.'}
$value=[ordered]@{schemaVersion=3;certified=$true;storySlug=$Story;certifiedAt=[DateTimeOffset]::UtcNow.ToString('o');certificationBasis='pipeline';artifacts=[ordered]@{story=[ordered]@{path='05-story.md'};canonDelta=[ordered]@{path='06-canon-delta.md'}};review=[ordered]@{artifact='05-story.md';pass=$cert.pass;verdict='PASS';reviewer='continuity_critic';reviewedAt=$(if(Test-PipelineTimestamp $cert.updated){$cert.updated}else{[DateTimeOffset]::UtcNow.ToString('o')});reviewBasis='independent continuity review';unresolvedCritical=0;unresolvedMajor=0};nameCheck=[ordered]@{story=$Story;phase='Final';passed=$true;checkedAt=$name.checkedAt;checkerVersion='story-names/3';warnings=@($name.warnings)};dependencies=[ordered]@{authorityManifest='authority.json';handoffLedger='handoffs.json'}}
Write-PipelineJson(Join-Path $dir 'release.json')$value;$value|ConvertTo-Json -Depth 12
