#Requires -Version 7.0
[CmdletBinding()]param([string]$Story,[ValidateSet('Text','Json')][string]$OutputFormat='Text',[string]$ProjectRoot)
$ErrorActionPreference='Stop';if([string]::IsNullOrWhiteSpace($ProjectRoot)){$ProjectRoot=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '../../../..'))}
. (Join-Path $PSScriptRoot 'PipelineCommon.ps1');. (Join-Path $PSScriptRoot 'PromotionContracts.ps1')
$errors=[Collections.Generic.List[string]]::new();$checked=0;$contract=$null;$acceptance=$null
try{$contract=Get-PipelineContract $ProjectRoot}catch{$errors.Add($_.Exception.Message)}
try{$acceptance=Get-LegacyAcceptance $ProjectRoot}catch{$errors.Add($_.Exception.Message)}
$indexPath=Join-Path $ProjectRoot 'stories/INDEX.md';$index=@{};try{$index=Get-IndexRows $indexPath}catch{$errors.Add($_.Exception.Message)};$registryLines=@(Get-Content -LiteralPath (Join-Path $ProjectRoot 'stories/NAMES.md'))
$dirs=if($Story){@((Get-Item -LiteralPath (Join-Path $ProjectRoot "stories/$Story")))}else{@(Get-ChildItem -LiteralPath (Join-Path $ProjectRoot 'stories')-Directory|Where-Object Name -ne '_template'|Sort-Object Name)}
foreach($dir in $dirs){$slug=$dir.Name;$checked++;try{
 $required=@('00-prompt.md','01-canon-brief.md','02-story-plan.md','03-draft.md','04-review.md','05-story.md','06-canon-delta.md','README.md','story.json','release.json');foreach($name in $required){if(-not(Test-Path -LiteralPath (Join-Path $dir.FullName $name) -PathType Leaf)){throw "required artifact '$name' is missing."}}
 $record=Read-PipelineJson(Join-Path $dir.FullName 'story.json');foreach($message in @(Test-StoryLifecycleRecord $record $contract)){throw $message};if($record.slug-cne$slug){throw 'directory slug and story.json disagree.'}
 $registryRows=@($registryLines|ForEach-Object{$parts=@($_.Trim('|').Split('|')|ForEach-Object{$_.Trim()});if($parts.Count-eq6-and$parts[2]-match"``$([regex]::Escape($slug))``"){,$parts}});if($record.status-ceq'final' -and @($registryRows|Where-Object{$_[3] -cne 'canon'}).Count){throw 'final canon story has a non-canon name-registry row.'}
 if(-not$index.ContainsKey($slug)){throw 'story is missing from INDEX.md.'};$row=$index[$slug];if($row.title-cne$record.title-or$row.status-cne$record.status-or$row.canon-cne$(if($record.canon){'yes'}else{'no'})-or$row.disposition-cne$record.userDisposition-or$row.publish-cne$(if($record.publish){'yes'}else{'no'})-or$row.promotionDate-cne$(if($record.promotionDate){$record.promotionDate}else{'—'})){throw 'INDEX.md projection disagrees with story.json.'}
 $readme=Get-Content -LiteralPath (Join-Path $dir.FullName 'README.md') -Raw;foreach($pair in @(@('Current stage',[string]$record.stage),@('Status',[string]$record.status),@('Canon',$(if($record.canon){'yes'}else{'no'})),@('User disposition',[string]$record.userDisposition),@('Publish',$(if($record.publish){'yes'}else{'no'})),@('Promotion date',$(if($record.promotionDate){[string]$record.promotionDate}else{'—'})))){if($readme -notmatch "(?m)^- $([regex]::Escape($pair[0])): $([regex]::Escape($pair[1]))\s*$"){throw "README projection for $($pair[0]) is stale."}}
 $release=Read-PipelineJson(Join-Path $dir.FullName 'release.json');Assert-PipelineFields $release @($contract.release.fields) 'release.json';if($release.schemaVersion-ne 3-or$release.storySlug-cne$slug){throw 'release identity/version is invalid.'};Assert-PipelineFields $release.artifacts @($contract.release.artifactContainerFields) 'release artifacts';Assert-PipelineFields $release.artifacts.story @('path') 'story artifact';Assert-PipelineFields $release.artifacts.canonDelta @('path') 'delta artifact';if($release.artifacts.story.path-cne'05-story.md'-or$release.artifacts.canonDelta.path-cne'06-canon-delta.md'){throw 'release artifact paths are invalid.'};Assert-PipelineFields $release.review @($contract.release.reviewFields) 'release review';Assert-PipelineFields $release.nameCheck @($contract.release.nameCheckFields) 'release name check';Assert-PipelineFields $release.dependencies @($contract.release.dependencyFields) 'release dependencies'
 if($record.status -cin @('candidate','final')){if($release.certified-ne$true-or-not(Test-PipelineTimestamp $release.certifiedAt)-or$release.review.verdict-cne'PASS'-or[int]$release.review.pass-lt1-or$release.review.unresolvedCritical-ne0-or$release.review.unresolvedMajor-ne0-or$release.nameCheck.passed-ne$true){throw 'terminal story does not have a valid simplified release.'}}
 if($record.provenance-ceq'legacy-user-attested'){if($null-eq$acceptance-or-not$acceptance.bySlug.ContainsKey($slug)){throw 'legacy story is not listed in legacy-acceptance.json.'};if($release.certificationBasis-cne'legacy-user-attested'){throw 'legacy release basis is invalid.'};if($record.status-cne'final'-or-not$record.canon-or-not$record.publish){throw 'accepted legacy story must be final, canon, and published.'};if($acceptance.bySlug[$slug].promotionDate-cne$record.promotionDate){throw 'legacy acceptance promotion date is stale.'};if($null-ne$release.dependencies.authorityManifest-or$null-ne$release.dependencies.handoffLedger){throw 'legacy release must not claim nonexistent pipeline dependencies.'}}
 else{if($release.certificationBasis-cne'pipeline'){throw 'pipeline release basis is invalid.'};foreach($name in @('authority.json','handoffs.json','promotion.json')){if(-not(Test-Path -LiteralPath (Join-Path $dir.FullName $name))){throw "pipeline artifact '$name' is missing."}};if($record.status-cne'in-progress'){& (Join-Path $PSScriptRoot 'Test-StoryHandoffs.ps1') -Story $slug -OutputFormat Json -ProjectRoot $ProjectRoot *> $null;$handoffOk=$?;if(-not $handoffOk){throw 'handoff ledger validation failed.'}};if($record.status-ceq'final'){$promotion=Read-PipelineJson(Join-Path $dir.FullName 'promotion.json');if($promotion.state-cne'completed'){throw 'pipeline final lacks a completed promotion.'}}}
 if(Test-Path -LiteralPath (Join-Path $dir.FullName 'promotion.json')){$p=Read-PipelineJson(Join-Path $dir.FullName 'promotion.json');Assert-PromotionRecord $p $slug}
}catch{$errors.Add("${slug}: $($_.Exception.Message)")}}
if(-not$Story){
 $dirSlugs=@($dirs.Name|Sort-Object);$indexSlugs=@($index.Keys|Sort-Object);foreach($slug in $dirSlugs){if($slug-cnotin$indexSlugs){$errors.Add("${slug}: directory is absent from index.")}};foreach($slug in $indexSlugs){if($slug-cnotin$dirSlugs){$errors.Add("${slug}: index row has no directory.")}}
 if($acceptance){$legacySlugs=@($dirs|ForEach-Object{$j=Read-PipelineJson(Join-Path $_.FullName 'story.json');if($j.provenance-ceq'legacy-user-attested'){$j.slug}}|Sort-Object);$accepted=@($acceptance.bySlug.Keys|Sort-Object);if(($legacySlugs-join"`n")-cne($accepted-join"`n")){$errors.Add('Legacy acceptance list does not exactly match legacy story records.')}}
 foreach($checker in @('Test-PipelineContract.ps1','Test-SourceManifest.ps1','Test-UniverseIntegrity.ps1')){$out=@(& (Join-Path $PSScriptRoot $checker) -OutputFormat Json -ProjectRoot $ProjectRoot 2>&1);$checkerOk=$?;if(-not $checkerOk){$errors.Add("Repository checker failed: $checker")}}
}
$result=[ordered]@{schemaVersion=1;passed=($errors.Count-eq0);checkedStories=$checked;errors=@($errors)}
if($OutputFormat-ceq'Json'){$result|ConvertTo-Json -Depth 10}else{if($result.passed){"Story integrity passed for $checked story record(s)."}else{$errors|ForEach-Object{"ERROR: $_"}}}
if(-not$result.passed){exit 1}
