#Requires -Version 7.0
[CmdletBinding()]param([Parameter(Mandatory)][string]$Story,[switch]$RequireReleaseChain,[ValidateSet('Text','Json')][string]$OutputFormat='Text',[string]$ProjectRoot)
$ErrorActionPreference='Stop';if([string]::IsNullOrWhiteSpace($ProjectRoot)){$ProjectRoot=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '../../../..'))}
. (Join-Path $PSScriptRoot 'PipelineCommon.ps1');$errors=[Collections.Generic.List[string]]::new();$unresolved=[Collections.Generic.List[object]]::new();$nonReady=[Collections.Generic.List[object]]::new();$releaseReady=$false;$ledger=$null
try{
 $contract=Get-PipelineContract $ProjectRoot;$path=Join-Path $ProjectRoot "stories/$Story/handoffs.json";$ledger=Read-PipelineJson $path;Assert-PipelineFields $ledger @($contract.handoffLedger.fields) 'handoffs.json'
 if($ledger.schemaVersion-ne$contract.handoffLedger.schemaVersion-or$ledger.storySlug-cne$Story){throw 'Handoff ledger identity/version is invalid.'}
 $entries=@($ledger.entries);$guardIds=@{};$latest=@{}
 for($i=0;$i-lt$entries.Count;$i++){
  $e=$entries[$i];Assert-PipelineFields $e @($contract.handoffLedger.entryFields) "handoff entry $($i+1)";if([int]$e.sequence-ne$i+1){$errors.Add("Handoff sequence must be contiguous at entry $($i+1).")};if($e.story-cne$Story){$errors.Add("Handoff entry $($i+1) has wrong story.")};if($guardIds.ContainsKey([string]$e.guardId)){$errors.Add("Duplicate guardId at entry $($i+1).")};$guardIds[[string]$e.guardId]=$true
  $mode=$contract.handoffLedger.modeContracts.PSObject.Properties[[string]$e.mode].Value;if($null-eq$mode){$errors.Add("Unknown mode at entry $($i+1).");continue};if($e.actor-cne$mode.actor-or$e.persister-cne$mode.persister){$errors.Add("Actor/persister mismatch at entry $($i+1).")};if([string]$e.status-cnotin@($mode.statuses)){$errors.Add("Status is invalid for mode at entry $($i+1).")}
  foreach($p in @($e.inputs)+@($e.outputs)){if($p-isnot[string]-or$p-match'(^|/)\.\.(/|$)'-or$p-match'^[\\/]'){$errors.Add("Unsafe path in handoff entry $($i+1).")}}
  $expected=@($mode.requiredInputs|ForEach-Object{$_.Replace('{story}',$Story)});if(@($expected|Where-Object{$_-cnotin@($e.inputs)}).Count-or@($e.inputs|Where-Object{$_-cnotin$expected}).Count){$errors.Add("Input contract mismatch at entry $($i+1).")};$allowed=@($mode.allowedOutputs|ForEach-Object{$_.Replace('{story}',$Story)});if(@($e.outputs|Where-Object{$_-cnotin$allowed}).Count){$errors.Add("Output contract mismatch at entry $($i+1).")};if($e.status-ceq'READY'-and$mode.requireAllReadyOutputs-and@($allowed|Where-Object{$_-cnotin@($e.outputs)}).Count){$errors.Add("READY entry $($i+1) did not produce every required output.")}
  if($e.report-isnot[string]-or[string]::IsNullOrWhiteSpace($e.report)){$errors.Add("Handoff entry $($i+1) lacks report text.")};if($e.status-ceq'READY'){if($null-ne$e.errorCode-or$null-ne$e.resolutionOwner-or$null-ne$e.resolutionQuestion){$errors.Add("READY entry $($i+1) has error or resolution fields.")};$latest[[string]$e.mode]=$e}else{if([string]::IsNullOrWhiteSpace([string]$e.errorCode)-or[string]::IsNullOrWhiteSpace([string]$e.resolutionOwner)){$errors.Add("Non-ready entry $($i+1) lacks error or resolution ownership.")};if($e.status-ceq'USER_RULING_REQUIRED'-and[string]::IsNullOrWhiteSpace([string]$e.resolutionQuestion)){$errors.Add("User-ruling entry $($i+1) lacks a resolution question.")};$nonReady.Add($e)}
 }
 foreach($e in $nonReady){$family=@($contract.handoffLedger.releaseFamilies|Where-Object{$e.mode-cin@($_)}|Select-Object -First 1);$laterReady=@($entries|Where-Object{$_.status-ceq'READY'-and[int]$_.sequence-gt[int]$e.sequence-and$family.Count-and$_.mode-cin@($family[0])});if(-not$laterReady.Count){$unresolved.Add([pscustomobject]@{sequence=$e.sequence;mode=$e.mode;status=$e.status})}}
 $familyReady=$true;$previousReadySequence=0;foreach($family in @($contract.handoffLedger.releaseFamilies)){$candidates=@($entries|Where-Object{$_.status-ceq'READY'-and$_.mode-cin@($family)}|Sort-Object {[int]$_.sequence} -Descending);if(-not$candidates.Count){$familyReady=$false;continue};$selected=$candidates[0];if([int]$selected.sequence-le$previousReadySequence){$familyReady=$false}else{$previousReadySequence=[int]$selected.sequence}}
 $releaseReady=($errors.Count-eq0-and$unresolved.Count-eq0-and$familyReady);if($RequireReleaseChain-and-not$releaseReady){$errors.Add('Handoff ledger does not contain a complete resolved release sequence.')}
}catch{$errors.Add($_.Exception.Message)}
$result=[ordered]@{schemaVersion=1;story=$Story;passed=($errors.Count-eq0);releaseReady=$releaseReady;entries=$(if($ledger){@($ledger.entries).Count}else{0});unresolved=@($unresolved);errors=@($errors)}
if($OutputFormat-ceq'Json'){$result|ConvertTo-Json -Depth 10}else{if($result.passed){"Handoff ledger passed for $Story."}else{$errors|ForEach-Object{"ERROR: $_"}}};if(-not$result.passed){exit 1}
