#Requires -Version 7.0
[CmdletBinding()]param([string]$Story,[ValidateSet('Automatic','Plan','Final')][string]$Phase='Automatic',[switch]$Strict,[switch]$SkipConfusable,[ValidateSet('Text','Json')][string]$OutputFormat='Text',[string]$ProjectRoot)
$ErrorActionPreference='Stop';if([string]::IsNullOrWhiteSpace($ProjectRoot)){$ProjectRoot=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot '../../../..'))}
. (Join-Path $PSScriptRoot 'PipelineCommon.ps1');$errors=[Collections.Generic.List[string]]::new();$warnings=[Collections.Generic.List[string]]::new()
if($Story -and $SkipConfusable){$errors.Add('Story-scoped name checks cannot skip confusable comparisons.')}
$path=Join-Path $ProjectRoot 'stories/NAMES.md';$rows=[Collections.Generic.List[object]]::new()
foreach($line in Get-Content -LiteralPath $path){if($line -notmatch '^\| ' -or $line -match '^\| ---'){continue};$parts=@($line.Trim('|').Split('|')|ForEach-Object{$_.Trim()});if($parts.Count -ne 6 -or $parts[0] -ceq 'Character / entity'){continue};$forms=@([regex]::Matches($parts[1],'`([^`]+)`')|ForEach-Object{$_.Groups[1].Value});$slugs=@([regex]::Matches($parts[2],'`([a-z0-9-]+)`')|ForEach-Object{$_.Groups[1].Value});$rows.Add([pscustomobject]@{name=$parts[0];forms=$forms;slugs=$slugs;state=$parts[3];reuse=$parts[4];rationale=$parts[5]})}
if($Story){$target=@($rows|Where-Object{$Story -cin $_.slugs});if(-not $target.Count){$errors.Add("No name-registry rows exist for $Story.")}
 foreach($row in $target){if($row.reuse -cnotin @('unique','deliberate','unresolved')){$errors.Add("Invalid reuse state for $($row.name).")};if($row.reuse -ceq 'unresolved'){$errors.Add("Unresolved name reuse for $($row.name).")};foreach($form in $row.forms){$collisions=@($rows|Where-Object{$_ -ne $row -and $form -cin $_.forms -and $_.state -cne 'released'});foreach($other in $collisions){if($row.reuse -cne 'deliberate' -or $other.reuse -cne 'deliberate'){$errors.Add("Undocumented exact name collision '$form' between $($row.name) and $($other.name).")}}}}
 if($Phase -ceq 'Automatic'){$Phase=if(Test-Path -LiteralPath (Join-Path $ProjectRoot "stories/$Story/05-story.md")){'Final'}else{'Plan'}}
 if($Phase -ceq 'Final'){$delta=Get-Content -LiteralPath (Join-Path $ProjectRoot "stories/$Story/06-canon-delta.md") -Raw;$storyText=Get-Content -LiteralPath (Join-Path $ProjectRoot "stories/$Story/05-story.md") -Raw;$inventory=$delta;if($delta -match '(?s)Final character-facing inventory:(?<v>.*?)(?:\n## |\z)'){$inventory=$Matches.v}else{$errors.Add('Final canon delta lacks a character-facing inventory.')};$inventoryForms=@([regex]::Matches($inventory,'`([^`]+)`')|ForEach-Object{$_.Groups[1].Value}|Sort-Object -Unique);$registered=@($target|ForEach-Object{$_.forms}|Sort-Object -Unique);foreach($form in $inventoryForms){if($form -cnotin $registered -and $form -cmatch '^[A-Z]'){$warnings.Add("Inventory label '$form' is not a registered character form.")}};foreach($form in $registered){if($storyText.IndexOf($form,[StringComparison]::OrdinalIgnoreCase)-lt 0){$errors.Add("Registered final form '$form' does not occur in final prose.")}}}
}else{if($Strict){$seen=@{};foreach($row in $rows){foreach($form in $row.forms){$key=$form.ToLowerInvariant();if($seen.ContainsKey($key) -and ($row.reuse -cne 'deliberate' -or $seen[$key].reuse -cne 'deliberate')){$errors.Add("Global name collision: $form")};$seen[$key]=$row}}}}
$result=[ordered]@{schemaVersion=1;checkerVersion='story-names/3';story=$(if($Story){$Story}else{$null});phase=$(if($Story){$Phase}else{'Global'});passed=($errors.Count -eq 0);checkedAt=[DateTimeOffset]::UtcNow.ToString('o');warnings=@($warnings);errors=@($errors)}
if($OutputFormat -ceq 'Json'){$result|ConvertTo-Json -Depth 8}else{if($result.passed){"Name check passed for $(if($Story){$Story}else{'registry'})."}else{$errors|ForEach-Object{"ERROR: $_"};$warnings|ForEach-Object{"WARNING: $_"}}}
if(-not $result.passed){exit 1}
