#Requires -Version 7.0
. (Join-Path $PSScriptRoot 'TestHelpers.ps1');$root=New-TestRoot 'authority'
try{
 Copy-Item (Join-Path $RepoRoot 'schemas') -Destination $root -Recurse;$null=New-Item -ItemType Directory -Path (Join-Path $root 'stories/sample') -Force;$null=New-Item -ItemType Directory -Path (Join-Path $root 'universe') -Force
 Write-TestJson (Join-Path $root 'stories/sample/story.json') ([ordered]@{slug='sample';status='in-progress';canon=$false});[IO.File]::WriteAllText((Join-Path $root 'universe/README.md'),'authority',[Text.UTF8Encoding]::new($false));Initialize-TestGit $root;Commit-TestGit $root 'base';& git -C $root update-ref refs/remotes/origin/main HEAD;& git -C $root checkout -q -b codex/story-sample
 $script=Join-Path $RepoRoot '.agents/skills/story-integrity/scripts/New-AuthorityManifest.ps1';$create=Invoke-TestScript $script @('-Story','sample','-ProjectRoot',$root,'-OutputFormat','Json');Assert-True $create.Succeeded $create.Output;$verify=Invoke-TestScript $script @('-Story','sample','-ProjectRoot',$root,'-Verify','-OutputFormat','Json');Assert-True $verify.Succeeded $verify.Output
 $newUniverse=Join-Path $root 'universe/new.md';[IO.File]::WriteAllText($newUniverse,'new',[Text.UTF8Encoding]::new($false));$inventoryStale=Invoke-TestScript $script @('-Story','sample','-ProjectRoot',$root,'-Verify','-OutputFormat','Json');Assert-True (-not$inventoryStale.Succeeded) 'Changed authority inventory was accepted.';Remove-Item -LiteralPath $newUniverse -Force;Commit-TestGit $root 'record authority'
 & git -C $root checkout -q main;[IO.File]::WriteAllText((Join-Path $root 'base-note.txt'),'advanced',[Text.UTF8Encoding]::new($false));Commit-TestGit $root 'advance base';& git -C $root update-ref refs/remotes/origin/main HEAD;& git -C $root checkout -q codex/story-sample;& git -C $root merge -q main
 $baseStale=Invoke-TestScript $script @('-Story','sample','-ProjectRoot',$root,'-Verify','-OutputFormat','Json');Assert-True (-not$baseStale.Succeeded) 'Stale authority base commit was accepted.';'Authority manifest tests passed.'
}finally{Remove-TestRoot $root}