#Requires -Version 7.0
. (Join-Path $PSScriptRoot 'TestHelpers.ps1');$root=New-TestRoot 'pr-policy'
try{
 Copy-Item (Join-Path $RepoRoot 'schemas') -Destination $root -Recurse;$null=New-Item -ItemType Directory -Path (Join-Path $root 'stories/sample') -Force;$null=New-Item -ItemType Directory -Path (Join-Path $root 'universe') -Force
 foreach($name in @('05-story.md','06-canon-delta.md','release.json','story.json','README.md')){[IO.File]::WriteAllText((Join-Path $root "stories/sample/$name"),"base $name`n",[Text.UTF8Encoding]::new($false))};[IO.File]::WriteAllText((Join-Path $root 'stories/sample/04-review.md'),"- Reviewed artifact: 05-story.md`n- Review pass: 1`n- Verdict: PASS`n- Updated: 2026-08-02T00:00:00Z`n",[Text.UTF8Encoding]::new($false));[IO.File]::WriteAllText((Join-Path $root 'stories/INDEX.md'),"base`n",[Text.UTF8Encoding]::new($false));[IO.File]::WriteAllText((Join-Path $root 'stories/NAMES.md'),"base`n",[Text.UTF8Encoding]::new($false));[IO.File]::WriteAllText((Join-Path $root 'universe/rules.md'),"base`n",[Text.UTF8Encoding]::new($false));Initialize-TestGit $root;Commit-TestGit $root 'base';$script=Join-Path $RepoRoot '.agents/skills/story-integrity/scripts/Test-PullRequestPolicy.ps1'
 $main=Invoke-TestScript $script @('-BaseRef','main','-HeadRef','HEAD','-OutputFormat','Json','-ProjectRoot',$root);Assert-True (-not$main.Succeeded) 'Direct main validation was accepted.'
 & git -C $root checkout -q -b codex/story-incomplete;Add-Content (Join-Path $root 'stories/sample/05-story.md') 'change';Commit-TestGit $root 'final only';$incomplete=Invoke-TestScript $script @('-BaseRef','main','-HeadRef','HEAD','-OutputFormat','Json','-ProjectRoot',$root);Assert-True (-not$incomplete.Succeeded) 'Final change without required co-changes was accepted.'
 & git -C $root checkout -q main;& git -C $root checkout -q -b codex/story-complete;foreach($name in @('05-story.md','06-canon-delta.md','04-review.md','release.json','story.json','README.md')){Add-Content (Join-Path $root "stories/sample/$name") 'cochange'};Add-Content (Join-Path $root 'stories/INDEX.md') 'cochange';Add-Content (Join-Path $root 'stories/NAMES.md') 'cochange';Commit-TestGit $root 'complete story update';$complete=Invoke-TestScript $script @('-BaseRef','main','-HeadRef','HEAD','-OutputFormat','Json','-ProjectRoot',$root);Assert-True $complete.Succeeded $complete.Output
 & git -C $root checkout -q main;& git -C $root checkout -q -b codex/story-history-cochanges;foreach($name in @('05-story.md','06-canon-delta.md','04-review.md','release.json','story.json','README.md')){Add-Content (Join-Path $root "stories/sample/$name") 'cochange'};Add-Content (Join-Path $root 'stories/INDEX.md') 'cochange';Add-Content (Join-Path $root 'stories/NAMES.md') 'cochange';Commit-TestGit $root 'complete story update';foreach($name in @('story.json','README.md')){[IO.File]::WriteAllText((Join-Path $root "stories/sample/$name"),"base $name`n",[Text.UTF8Encoding]::new($false))};[IO.File]::WriteAllText((Join-Path $root 'stories/INDEX.md'),"base`n",[Text.UTF8Encoding]::new($false));Commit-TestGit $root 'restore unchanged projections';$history=Invoke-TestScript $script @('-BaseRef','main','-HeadRef','HEAD','-OutputFormat','Json','-ProjectRoot',$root);Assert-True $history.Succeeded $history.Output
 & git -C $root checkout -q main;& git -C $root checkout -q -b codex/universe-without-promotion;Add-Content (Join-Path $root 'universe/rules.md') 'change';Commit-TestGit $root 'universe only';$universe=Invoke-TestScript $script @('-BaseRef','main','-HeadRef','HEAD','-OutputFormat','Json','-ProjectRoot',$root);Assert-True (-not$universe.Succeeded) 'Universe change without promotion was accepted.';'Pull-request policy tests passed.'
}finally{Remove-TestRoot $root}
