"""Illustrated edition rendering and frozen publication snapshots.

Artwork is generated by the edition agent. This module only composes existing
art and unchanged Markdown; Pages builds never open production packages.
"""
from __future__ import annotations

import argparse
import hashlib
import html
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path, PurePosixPath
from xml.etree import ElementTree as ET

import markdown
from markdown.extensions import Extension
from markdown.treeprocessors import Treeprocessor
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SNAPSHOT = ROOT / 'pages/illustrated.json'
MODES = {'classic', 'deluxe', 'cinematic'}
LAYOUTS = {'inline', 'full-page', 'spot'}
SLUG = re.compile(r'^[a-z0-9]+(?:-[a-z0-9]+)*$')


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def safe_path(root: Path, value: str) -> Path:
    part = PurePosixPath(value)
    if not value or ':' in value or '\\' in value or part.is_absolute() or any(p in {'.', '..'} for p in part.parts):
        raise ValueError(f'Unsafe asset path: {value}')
    target = (root / value).resolve()
    if root.resolve() not in target.parents:
        raise ValueError(f'Asset escapes its root: {value}')
    return target


def prose_body(body: str, title: str) -> str:
    """Only an exact redundant leading title is presentation metadata."""
    body = body.replace('\r\n', '\n').replace('\r', '\n')
    match = re.match(r'^(?:[ \t]*\n)* {0,3}# +([^\n]+)(?:\n|$)', body)
    if match and match[1].strip() == title.strip():
        return body[match.end():]
    return body


class _Illustrations(Treeprocessor):
    def __init__(self, md, entries, asset_prefix):
        super().__init__(md)
        self.entries = entries
        self.asset_prefix = asset_prefix
        self.anchors = []

    def run(self, root):
        original = list(root)
        by_anchor = {}
        ids = set()
        for entry in self.entries:
            if entry['id'] in ids:
                raise ValueError('Duplicate illustration ID')
            ids.add(entry['id'])
            if entry.get('layout', 'inline') not in LAYOUTS or not entry.get('alt', '').strip():
                raise ValueError('Illustrations require a valid layout and descriptive alt text')
            by_anchor.setdefault(entry['after'], []).append(entry)
        for index, element in enumerate(original, 1):
            raw = ET.tostring(element, encoding='unicode')
            anchor = f'b{index:04d}-' + hashlib.sha256(raw.encode()).hexdigest()[:12]
            self.anchors.append({'id': anchor, 'tag': element.tag, 'text': ''.join(element.itertext())})
            element.set('data-source-block', anchor)
            position = list(root).index(element) + 1
            for entry in by_anchor.pop(anchor, []):
                figure = ET.Element('figure', {'class': 'edition-art ' + entry.get('layout', 'inline'), 'data-art-id': entry['id']})
                ET.SubElement(figure, 'img', {
                    'src': self.asset_prefix + entry['path'], 'alt': entry['alt'],
                    'loading': 'lazy', 'decoding': 'async',
                })
                if entry.get('caption'):
                    ET.SubElement(figure, 'figcaption').text = entry['caption']
                root.insert(position, figure)
                position += 1
        if by_anchor:
            raise ValueError('Unknown or stale illustration anchor: ' + ', '.join(by_anchor))
        return root


class _EditionExtension(Extension):
    def __init__(self, entries, prefix):
        super().__init__()
        self.entries, self.prefix = entries, prefix
        self.processor = None

    def extendMarkdown(self, md):
        self.processor = _Illustrations(md, self.entries, self.prefix)
        md.treeprocessors.register(self.processor, 'edition-illustrations', -10)


def _markdown(body, title, entries, prefix):
    extension = _EditionExtension(entries, prefix)
    result = markdown.markdown(prose_body(body, title), extensions=['extra', extension], output_format='html')
    return result, extension.processor.anchors


def block_anchors(body: str, title: str) -> list[dict]:
    return _markdown(body, title, [], '')[1]


def render_prose(body: str, title: str, illustrations: list[dict], asset_prefix: str = '') -> str:
    return _markdown(body, title, illustrations, asset_prefix)[0]


def render_document(record: dict, *, stylesheet='../illustrated.css', asset_prefix='../', navigation=True, writing_prompt='', comic=None) -> str:
    from pages.graphic_novels import download_link
    title = html.escape(record['title'])
    pdf_link = (
        f'<p class="edition-download"><a href="{html.escape(asset_prefix + record["pdf"]["path"], quote=True)}" download>Download PDF</a></p>'
        if navigation and record.get('pdf') else ''
    )
    comic_link = download_link(comic, asset_prefix) if navigation else ''
    author = f'<p class="edition-author">{html.escape(record["author"])}</p>' if record.get('author') else ''
    prompt = ('<section class="edition-prompt" aria-labelledby="writing-prompt-title">'
              '<h2 id="writing-prompt-title">Writing Prompt</h2>'
              f'<blockquote>{html.escape(writing_prompt)}</blockquote></section>') if writing_prompt else ''
    cover = html.escape(asset_prefix + record['cover']['path'], quote=True)
    prose = render_prose(record['body'], record['title'], record['illustrations'], asset_prefix)
    mode = record['mode']
    if mode not in MODES:
        raise ValueError('Invalid presentation mode')
    body = (f'<section class="edition-cover"><img src="{cover}" alt="Cover for {title}"></section>'
            f'<header class="edition-title"><p class="edition-label">{mode.title()} illustrated edition</p><h1>{title}</h1>{author}{pdf_link}{comic_link}</header>'
            f'{prompt}'
            f'<article class="edition-prose" aria-label="Story">{prose}</article>'
            '<p class="edition-end" aria-label="End of story">◆</p>')
    if navigation:
        from pages.build import _page
        return _page(
            record['title'] + ' — Illustrated Edition', body,
            asset_prefix + 'index.html', asset_prefix + 'styles.css', asset_prefix + 'theme.js',
            extra_stylesheet_hrefs=(stylesheet,), body_class='edition-page', main_class=f'edition mode-{mode}',
        )
    return ('<!doctype html><html lang="en"><head><meta charset="utf-8">'
            '<meta name="viewport" content="width=device-width,initial-scale=1">'
            f'<title>{title} — Illustrated Edition</title>'
            f'<link rel="stylesheet" href="{html.escape(stylesheet, quote=True)}">'
            f'</head><body class="edition-standalone"><main class="edition mode-{mode}">{body}</main></body></html>')


def _public_asset(entry, relative):
    return {key: entry[key] for key in ('id', 'sha256', 'after', 'layout', 'alt', 'caption') if key in entry} | {'path': relative}


def _record(root: Path, manifest: dict) -> dict:
    from illustrated.edition import get_source_body, pdf_requested
    slug = manifest['slug']
    return {
        'slug': slug, 'title': manifest['title'], 'mode': manifest['mode'].lower(),
        'source': {k:v for k,v in manifest['source'].items() if k in {'slug','title','layout','commit','prose','files','bodySha256'}}, 'body': get_source_body(root, manifest),
        'cover': _public_asset(manifest['cover'], f'illustrated/{slug}/cover' + Path(manifest['cover']['path']).suffix),
        'illustrations': [_public_asset(a, f'illustrated/{slug}/' + a['path']) for a in manifest['illustrations']],
        **({'pdf': {'path': f'illustrated/{slug}/edition.pdf', 'sha256': (manifest.get('render') or {}).get('pdfSha256', '')}} if pdf_requested(manifest) else {}),
    }


def render_edition(root: Path, slug: str) -> Path:
    from illustrated.edition import validate_edition, stage_digest, save_edition, require_worktree, pdf_requested, get_public_prompt
    require_worktree(root)
    manifest = validate_edition(root, slug, 'render')
    directory = root / 'illustrated' / slug
    record = _record(root, manifest)
    input_hash = stage_digest(root, manifest, 'render')
    writing_prompt = get_public_prompt(root, manifest['source']['slug'])
    document_html = render_document(record, writing_prompt=writing_prompt)
    if not pdf_requested(manifest):
        target = directory / 'edition.html'
        target.write_text(document_html, encoding='utf-8', newline='\n')
        manifest['render'] = {'inputsSha256': input_hash, 'htmlSha256': digest(target)}
        manifest.get('approvals', {}).pop('final', None)
        manifest.pop('review', None)
        save_edition(root, manifest)
        return target
    # The preview is disposable. Only the final PDF and its bound digest are kept.
    with tempfile.TemporaryDirectory(prefix='illustrated-export-') as temporary:
        preview = Path(temporary)
        for asset, target in [(manifest['cover'], record['cover'])] + list(zip(manifest['illustrations'], record['illustrations'])):
            destination = safe_path(preview, target['path'])
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(safe_path(directory, asset['path']), destination)
        shutil.copyfile(ROOT / 'pages/illustrated.css', preview / 'illustrated.css')
        shutil.copytree(ROOT / 'pages/fonts', preview / 'fonts')
        document = preview / 'edition.html'
        document.write_text(render_document(record, stylesheet='illustrated.css', asset_prefix='', navigation=False, writing_prompt=writing_prompt), encoding='utf-8')
        pdf = preview / 'edition.pdf'
        subprocess.run(['node', str(ROOT / 'illustrated/export.mjs'), str(document), str(pdf)], check=True)
        # Check inputs again after the potentially lengthy browser operation.
        current = validate_edition(root, slug, 'render')
        if stage_digest(root, current, 'render') != input_hash:
            raise ValueError('Edition changed during export')
        shutil.copyfile(pdf, directory / 'edition.pdf')
    (directory / 'edition.html').write_text(document_html, encoding='utf-8', newline='\n')
    current['render'] = {'inputsSha256': input_hash, 'htmlSha256': digest(directory / 'edition.html'), 'pdfSha256': digest(directory / 'edition.pdf')}
    current.get('approvals', {}).pop('final', None)
    current.pop('review', None)
    save_edition(root, current)
    return directory / 'edition.pdf'


def preview_edition(root: Path, slug: str, destination: Path) -> Path:
    """Write a disposable web preview, never into production or captured assets."""
    from illustrated.edition import validate_edition, require_worktree
    from pages.build import build, load_story_source, prepare_output, render_story, render_index
    require_worktree(root)
    manifest = validate_edition(root, slug, 'render')
    out = prepare_output(destination, root)
    catalog = build(out, root / 'pages/catalog.json')
    record = _record(root, manifest)
    # Preview the working edition against a disposable copy of the published
    # library, so navigation and theme controls behave as they do on Pages.
    # An unpublished original may also be viewed here without capturing it.
    source = next((story for story in catalog.stories if story.slug == manifest['source']['slug']), None)
    if source is None:
        source = load_story_source(manifest['source']['slug'], root)
        shutil.copyfile(root / 'stories' / source.slug / 'title-image.jpg', safe_path(out, source.cover))
    for asset, target in [(manifest['cover'], record['cover'])] + list(zip(manifest['illustrations'], record['illustrations'])):
        path = safe_path(out, target['path'])
        path.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(safe_path(root / 'illustrated' / slug, asset['path']), path)
    if record.get('pdf') and (root / 'illustrated' / slug / 'edition.pdf').exists():
        shutil.copyfile(root / 'illustrated' / slug / 'edition.pdf', safe_path(out, record['pdf']['path']))
    shutil.copyfile(ROOT / 'pages/illustrated.css', out / 'illustrated.css')
    shutil.copytree(ROOT / 'pages/fonts', out / 'fonts', dirs_exist_ok=True)
    target = out / 'stories' / f'{source.slug}.html'
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render_story(source, [record]), encoding='utf-8', newline='\n')
    if source.slug in {story.slug for story in catalog.stories}:
        records = [item for item in load_snapshot(root / 'pages/illustrated.json') if item['source']['slug'] != source.slug] + [record]
        (out / 'index.html').write_text(render_index(catalog, records), encoding='utf-8', newline='\n')
    return target



def layout_sample(root: Path, slug: str, destination: Path) -> Path:
    """Show real typography before scene generation, using an accepted reference."""
    from illustrated.edition import validate_edition, require_worktree, _require_approval, _check_asset
    from pages.build import build, load_story_source, prepare_output, render_index, render_story
    require_worktree(root)
    manifest = validate_edition(root, slug, 'plan')
    _require_approval(root, manifest, 'plan')
    _check_asset(root, manifest, manifest['cover'])
    directory = root / 'illustrated' / slug
    out = prepare_output(destination, root)
    catalog = build(out, root / 'pages/catalog.json')
    record = _record(root, manifest)
    # A pilot may settle the hardest composition before the remaining reference
    # sheets are generated. Only the displayed assets must be accepted here.
    pilot_id = (manifest.get('productionPolicy') or {}).get('pilotAssetId')
    sample = next((a for a in manifest['illustrations'] if a['id'] == pilot_id and a.get('accepted')), None)
    sample = sample or next((a for a in manifest['references'] if a.get('accepted')), None)
    if sample is None:
        raise ValueError('Accept a reference or the planned pilot illustration before making a layout sample')
    _check_asset(root, manifest, sample)
    sample_path = safe_path(directory, sample['path'])
    if not sample_path.is_file():
        raise ValueError('Accept a reference or the reused cover before making a layout sample')
    cover_path = safe_path(out, record['cover']['path'])
    cover_path.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(safe_path(directory, manifest['cover']['path']), cover_path)
    sample_target = f'illustrated/{slug}/sample' + sample_path.suffix
    shutil.copyfile(sample_path, safe_path(out, sample_target))
    anchors = block_anchors(record['body'], record['title'])
    is_pilot = sample['id'] == pilot_id
    record['illustrations'] = [{
        'id':'layout-sample', 'after':sample['after'] if is_pilot else anchors[0]['id'], 'path':sample_target,
        'layout':sample.get('layout', 'inline') if is_pilot else ('full-page' if record['mode']=='cinematic' else 'inline'),
        'alt':sample['alt'] if is_pilot else 'Approved visual reference used to demonstrate page layout.',
        **({'caption': sample['caption']} if is_pilot and sample.get('caption') else {}),
        **({'caption':'Layout preview: reference artwork; scene illustrations will follow approval.'} if not is_pilot else {}),
    }]
    # A sample must never advertise a PDF that has not been rendered yet.
    record.pop('pdf', None)
    shutil.copyfile(ROOT/'pages/illustrated.css', out/'illustrated.css')
    shutil.copytree(ROOT/'pages/fonts',out/'fonts', dirs_exist_ok=True)
    source = next((story for story in catalog.stories if story.slug == manifest['source']['slug']), None)
    if source is None:
        source = load_story_source(manifest['source']['slug'], root)
    target = out / 'stories' / f'{source.slug}.html'
    target.write_text(render_story(source, [record]), encoding='utf-8', newline='\n')
    if source.slug in {story.slug for story in catalog.stories}:
        records = [item for item in load_snapshot(root / 'pages/illustrated.json') if item['source']['slug'] != source.slug] + [record]
        (out / 'index.html').write_text(render_index(catalog, records), encoding='utf-8', newline='\n')
    return target


def load_snapshot(path: Path = SNAPSHOT) -> list[dict]:
    if not path.exists():
        return []
    data = json.loads(path.read_text(encoding='utf-8-sig'))
    if set(data) != {'schemaVersion', 'editions'} or data['schemaVersion'] != 1 or not isinstance(data['editions'], list):
        raise ValueError('Invalid illustrated snapshot')
    seen = set()
    sources = set()
    for record in data['editions']:
        if set(record) not in ({'slug', 'title', 'mode', 'source', 'body', 'cover', 'illustrations'}, {'slug', 'title', 'mode', 'source', 'body', 'cover', 'illustrations', 'pdf'}):
            raise ValueError('Invalid illustrated snapshot fields')
        slug = record['slug']
        if not SLUG.fullmatch(slug) or slug in seen or record['mode'] not in MODES:
            raise ValueError('Duplicate or invalid illustrated edition')
        seen.add(slug)
        if not isinstance(record['body'], str) or not record['body'].strip() or not SLUG.fullmatch(record['source']['slug']):
            raise ValueError('Invalid illustrated source')
        if record['source']['slug'] in sources:
            raise ValueError('Only one published illustrated edition is allowed per source story')
        sources.add(record['source']['slug'])
        if hashlib.sha256(record['body'].encode('utf-8')).hexdigest() != record['source']['bodySha256']:
            raise ValueError('Captured prose differs from its pinned source digest')
        render_prose(record['body'], record['title'], record['illustrations'])
        for asset in published_assets(record):
            if not asset['path'].startswith(f'illustrated/{slug}/'):
                raise ValueError('Captured asset belongs to another edition')
            target = safe_path(path.parent, asset['path'])
            if not target.is_file() or digest(target) != asset['sha256']:
                raise ValueError(f'Captured asset missing or changed: {asset["path"]}')
            if asset is record.get('pdf'):
                if not target.read_bytes().startswith(b'%PDF-'):
                    raise ValueError('Invalid captured PDF')
            else:
                with Image.open(target) as image:
                    image.verify()
    return data['editions']


def published_assets(record: dict) -> list[dict]:
    return [record['cover'], *record['illustrations'], *([record['pdf']] if record.get('pdf') else [])]


def capture_edition(root: Path, slug: str, snapshot: Path | None = None) -> dict:
    from illustrated.edition import validate_edition, require_worktree
    require_worktree(root)
    from pages.build import load_catalog, published_canon_marker_conflicts
    snapshot = snapshot or root / 'pages/illustrated.json'
    manifest = validate_edition(root, slug, 'final')
    directory = root / 'illustrated' / slug
    catalog = load_catalog(snapshot.parent / 'catalog.json')
    source_slug = manifest['source']['slug']
    if source_slug not in {s.slug for s in catalog.stories}:
        raise ValueError('Publish the named original story before capturing its edition')
    # Existing canon reconciliation stays authoritative; capture cannot demote a source.
    conflicts = published_canon_marker_conflicts(catalog, root)
    if source_slug in conflicts:
        raise ValueError('Reconcile the named source/catalog canon state before capture')
    records = load_snapshot(snapshot)
    record = _record(root, manifest)
    render_prose(record['body'], record['title'], record['illustrations'])
    records = sorted([r for r in records if r['slug'] != slug and r['source']['slug'] != source_slug] + [record], key=lambda r: r['slug'])
    target_directory = safe_path(snapshot.parent, f'illustrated/{slug}')
    target_directory.parent.mkdir(parents=True, exist_ok=True)
    # Stage every byte before touching a published edition. A failed replacement
    # restores both the old asset directory and catalog.
    previous_snapshot = snapshot.read_bytes() if snapshot.exists() else None
    with tempfile.TemporaryDirectory(prefix='.edition-capture-', dir=snapshot.parent) as temporary:
        staging = Path(temporary)
        staged_assets = staging / 'assets'
        staged_assets.mkdir()
        for source, target in [(manifest['cover'], record['cover']), *zip(manifest['illustrations'], record['illustrations']), *([({'path':'edition.pdf'},record['pdf'])] if record.get('pdf') else [])]:
            relative = target['path'].removeprefix(f'illustrated/{slug}/')
            destination = safe_path(staged_assets, relative)
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(safe_path(directory, source['path']), destination)
            if digest(destination) != target['sha256']:
                raise ValueError('Edition asset changed during capture')
        validate_edition(root, slug, 'final')
        staged_snapshot = staging / 'snapshot.json'
        staged_snapshot.write_text(json.dumps({'schemaVersion':1,'editions':records},ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
        backup = staging / 'previous-assets'
        installed = False
        try:
            if target_directory.exists(): os.replace(target_directory, backup)
            os.replace(staged_assets, target_directory)
            installed = True
            os.replace(staged_snapshot, snapshot)
            load_snapshot(snapshot)
        except Exception:
            if installed: shutil.rmtree(target_directory)
            if backup.exists(): os.replace(backup,target_directory)
            if previous_snapshot is None:
                snapshot.unlink(missing_ok=True)
            else:
                snapshot.write_bytes(previous_snapshot)
            raise

    return record


def check_snapshot(root: Path, snapshot: Path | None = None) -> list[str]:
    """Check stored bytes; newer source/production versions do not rewrite publication."""
    snapshot = snapshot or root / 'pages/illustrated.json'
    records = load_snapshot(snapshot)
    notes = []
    for record in records:
        directory = root / 'illustrated' / record['slug']
        if not (directory / 'edition.json').is_file():
            raise ValueError(f'Missing source edition {record["slug"]}')
        from illustrated.edition import load_edition, stage_digest, verify_source
        current = load_edition(root, record['slug'])
        render = current.get('render') or {}
        approval = current.get('approvals', {}).get('final') or {}
        still_approved = (
            render.get('pdfSha256') == record.get('pdf', {}).get('sha256')
            and render.get('inputsSha256') == stage_digest(root,current,'render')
            and approval.get('inputsSha256') == stage_digest(root,current,'final')
        )
        if not still_approved:
            notes.append(f'{record["slug"]}: publication retains its approved earlier edition')
            continue
        if record.get('pdf') and digest(directory/'edition.pdf') != record['pdf']['sha256']:
            raise ValueError(f'Production/capture PDF mismatch: {record["slug"]}')
        source_identity = {k:v for k,v in current['source'].items() if k in {'slug','title','layout','commit','prose','files','bodySha256'}}
        if current['title'] != record['title'] or current['mode'].lower() != record['mode'] or source_identity != record['source']:
            raise ValueError('Production/capture edition identity mismatch')
        live_art = [current['cover'], *current['illustrations']]
        stored_art = [record['cover'], *record['illustrations']]
        if [a['id'] for a in live_art] != [a['id'] for a in stored_art]:
            raise ValueError('Production/capture illustration inventory mismatch')
        for source, stored in zip(live_art, stored_art, strict=True):
            expected_path = f'illustrated/{record["slug"]}/cover' + Path(source['path']).suffix if source['id']=='cover' else f'illustrated/{record["slug"]}/' + source['path']
            if stored['path'] != expected_path or source['sha256'] != stored['sha256'] or digest(safe_path(directory,source['path'])) != stored['sha256']:
                raise ValueError(f'Production/capture asset mismatch: {source["path"]}')
            for key in ('after','layout','alt','caption'):
                if source.get(key) != stored.get(key):
                    raise ValueError('Production/capture placement or accessibility text mismatch')
        try:
            verify_source(root,current)
        except ValueError:
            notes.append(f'{record["slug"]}: source has changed; publication retains its approved version')

    return notes


def build_editions(output: Path, snapshot: Path) -> list[dict]:
    records = load_snapshot(snapshot)
    if not records:
        return records
    (output / 'illustrated').mkdir(exist_ok=True)
    shutil.copyfile(ROOT / 'pages/illustrated.css', output / 'illustrated.css')
    shutil.copytree(ROOT / 'pages/fonts', output / 'fonts')
    for record in records:
        for asset in published_assets(record):
            target = safe_path(output, asset['path'])
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(safe_path(snapshot.parent, asset['path']), target)
    return records


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--root', type=Path, default=ROOT)
    commands = parser.add_subparsers(dest='command', required=True)
    anchors = commands.add_parser('anchors')
    anchors.add_argument('slug')
    render = commands.add_parser('render')
    render.add_argument('slug')
    sample = commands.add_parser('layout-sample')
    sample.add_argument('slug')
    sample.add_argument('--output', required=True, type=Path)
    preview = commands.add_parser('preview')
    preview.add_argument('slug')
    preview.add_argument('--output', required=True, type=Path)
    args = parser.parse_args()
    if args.command == 'render':
        print(render_edition(args.root, args.slug))
    elif args.command == 'layout-sample':
        print(layout_sample(args.root, args.slug, args.output))
    elif args.command == 'preview':
        print(preview_edition(args.root, args.slug, args.output))
    else:
        from illustrated.edition import load_edition, get_source_body
        manifest = load_edition(args.root, args.slug)
        print(json.dumps(block_anchors(get_source_body(args.root, manifest), manifest['title']), ensure_ascii=False, indent=2))


if __name__ == '__main__':
    sys.path.insert(0, str(ROOT))
    main()
